plugins {
    id 'com.gtnewhorizons.gtnhconvention'
    id 'signing'
}

tasks.register('signJar') {
    dependsOn reobfJar
    def keyStore = System.env.MC_KS_PATH
    onlyIf { // Skip the task if our secret data isn't available
        System.env.MC_KS_PASS != null
    }
    def alias = System.env.MC_KS_ALIAS
    def storePass = System.env.MC_KS_PASS
    def keyPass = System.env.MC_KS_PASS

    doLast {
        def libsDir = jar.destinationDirectory.get().asFile
        def signPath = new File(libsDir, "signed")
        mkdir signPath.toString()
        reobfJar.outputs.files.files.each {
            println("Signing $it...")
            ant.signjar destDir: signPath,
                    sigfile: alias,
                    keystore: keyStore,
                    alias: alias,
                    storepass: storePass,
                    keypass: keyPass,
                    jar: it
            println("Moving $it back!")
        }
        signPath.listFiles().each {
            def unsigned = new File(libsDir, it.name)
            if (unsigned.delete()) println("Deleted unsigned version.")
            it.renameTo(unsigned)
        }
    }
}

reobfJar.finalizedBy signJar