plugins {
    id 'com.gtnewhorizons.gtnhconvention'
    id 'signing'
}

tasks.register('signJar') {
    dependsOn reobfJar
    def keyStore = System.env.MC_KS_PATH
    onlyIf { // Skip the task if our secret data isn't available
        System.env.MC_KS_PASS != null
    }
    def alias = System.env.MC_KS_ALIAS
    def storePass = System.env.MC_KS_PASS
    def keyPass = System.env.MC_KS_PASS

    doLast {
        def signPath = new File(jar.destinationDirectory.get().asFile, "signed")
        mkdir signPath.toString()
        reobfJar.outputs.files.files.each {
            println("Signing $it...")
            ant.signjar destDir: signPath,
                    sigfile: alias,
                    keystore: keyStore,
                    alias: alias,
                    storepass: storePass,
                    keypass: keyPass,
                    jar: it
        }
    }
}

reobfJar.finalizedBy signJar